---
language: python
python: "2.7"

sudo: required

services:
  - docker

before_install:
  - echo -e "{\"Ubuntu\": \"$UBUNTU_SUBSCRIPTION\", \"CentOS\": \"$CENTOS_SUBSCRIPTION\"}" > tests/subscriptions.json

script:
  - make test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
