---
- name: Check if already active.
  command: "docker info --format '{{ '{{' }}.Swarm.LocalNodeState {{ '}}' }}'"
  register: _swarm_node_status

- name: Join Docker Swarm.
  command: docker swarm join --token "{{ hostvars[groups[docker_swarm_leader][0]][docker_swarm_token_type].stdout }}" "{{ hostvars[groups[docker_swarm_leader][0]]['ansible_default_ipv4']['address'] }}"
  when: _swarm_node_status.stdout == "inactive"
