---

#
# Check Docker Swarm current state.
#

- name: Check if already active
  command: "docker info --format '{{ '{{' }}.Swarm.LocalNodeState {{ '}}' }}'"
  register: activity_status

#
# Initialize Docker Swarm.
#

- name: Initialize swarm.
  command: docker swarm init
  when: activity_status.stdout == "inactive"

#
# Export tokens.
#

- name: Export manager token.
  command: docker swarm join-token manager -q
  register: swarm-manager-token

- name: Export worker token.
  command: docker swarm join-token worker -q
  register: swarm-worker-token
