---
- name: Install Ansible pip requirements.
  yum:
    name: "{{ package }}"
    state: present
  become: sudo
  with_items:
    - python
    - python-pip
    - python-virtualenv
  loop_control:
    loop_var: package
  tags:
    - python
    - python2
    - virtualenv
    - pip

- pip:
    name: "{{ module }}"
  with_items:
    - setuptools
    - docker-py
  loop_control:
    loop_var: module
  tags:
    - docker-py
